### PR TITLE
(MAINT) Fix Cursor #save in AppVeyor testing

### PR DESCRIPTION
**Pull request by austb**

### CODE REVIEW

**Comment by austb** [comment]
Unfortunately, it looks like AppVeyor w/ Ruby 1.9.3 is failing because of Gem dependencies

**Comment by piotrmurach** [comment]
That's fine, it is expected in the test matrix.

**Comment by piotrmurach** [comment]
I was kind of thinking about the `win_platform` check. The danger here is with cygwin emulators and such, which should be compatible with major terminals. In any case, I'm happy to release. Btw I've tried this version with `tty-spinner` using save & restore in write and it seems to work fine.

**Comment by piotrmurach** [comment]
Do you have anything else to add before release?

**Comment by austb** [comment]
Nope, I'll go switch my TTY::Spinner PR back to using #save and #restore. Thanks!

**Comment by piotrmurach** [comment]
Released `v0.5.0`

**Pull request merged**
